################################################################################
## File name: cleaning_claims.R                                               ##
## Author:    Maximillian Mantei                                              ##
## Date:      2015-08-04                                                      ##
## Purpose:   cleaning claims data                                            ##
################################################################################

## Loading packages
library(dplyr)
library(xlsx)

## Set working directory
wd <- "C:/GitHub/ICSID_claims/"
setwd(wd)

## RUN pulling_claims.R FIRST IF cases_fresh.csv DOES NOT EXIST!
# source("pulling_claims.R")

## Load the data generated by pulling_claims.R
cases <- read.csv("data/cases_fresh.csv", stringsAsFactors = FALSE)

## extract info and reformat variables
# year the claim was registered
cases$reg_year <- sapply(cases$registered, function(x){
      y <- strsplit(x, ", ")[[1]][2] # splits string at the ", "
      substr(y, 1,  4)} # cuts off everything that might come after the year
) %>% as.numeric() # converts string to number
# year the original case was concluded (or discontinued)
cases$out_year <- sapply(cases$outcome, function(x){
      y <- strsplit(x, ", ")[[1]][2] # splits string at the ", "
      substr(y, 1,  4)} # cuts off everything that might come after the year
) %>% as.numeric() # converts string to number
# creates a dummy; = 1 if there is a BIT invoked
cases$bit_claim <- as.numeric(cases$bit != "")
# creates a dummy; = 1 if instruments contains NAFTA
cases$nafta_claim <- as.numeric(grepl("NAFTA",cases$instrument))
# creates a dummy; = 1 if the claim is neither BIT nor NAFTA
cases$other_claim <- as.numeric((cases$bit_claim + cases$nafta_claim) == 0)

## get claimant natinalities (add every claimant in new row)
# extract whats between brackets in the claimants variable
claimants_list <- regmatches(cases$claimants, 
                             gregexpr("(?=\\().*?(?<=\\))",
                                      cases$claimants, perl=T))
# remove remaining brackets on the new variable
claimants_list <- lapply(claimants_list, function(x){
      gsub("[\\(\\)]", "",x)}
)
# get possibly more nationalities (i.e. when 2 countries are in one pair of brackets)
claimants_list <- lapply(claimants_list, function(x){
      x <- unlist(strsplit(x, split = ", "))
      unique(x) # get the unique values (when more than 2 companies are from same country)
})
# append the data by the number of claimants per case
cases <- cases[rep(1:nrow(cases), sapply(claimants_list, function(x){length(x)})),]
# add all claimants to the data
cases$claimants_nat <- unlist(claimants_list)

# correcting quirks in the claimants nationalities
cases$claimants_nat[cases$claimants_nat == "nationality not available"] <- NA
cases$claimants_nat[cases$claimants_nat == "Pty"] <- NA
cases$claimants_nat[cases$claimants_nat == "Panamá"] <- "Panama"
cases$claimants_nat[cases$claimants_nat == "Tallinn"] <- "Estonia"
cases$claimants_nat[cases$claimants_nat == "Indian Ocean"] <- NA
cases$claimants_nat[cases$claimants_nat == "Block A1"] <- NA
cases$claimants_nat[cases$claimants_nat == "Block A4"] <- NA
cases$claimants_nat[cases$claimants_nat == "G.P."] <- NA
cases$claimants_nat[cases$claimants_nat == "Lithuanian"] <- "Lithuania"
cases$claimants_nat[cases$claimants_nat == "G.P."] <- NA
cases$claimants_nat[cases$claimants_nat == "Group"] <- NA
cases$claimants_nat[cases$claimants_nat == "08-10"] <- NA
cases$claimants_nat[cases$claimants_nat == "Holding"] <- NA
cases$claimants_nat[cases$claimants_nat == "Pigap II"] <- NA
cases$claimants_nat[cases$claimants_nat == "Private"] <- NA
cases$claimants_nat[cases$claimants_nat == "Uruguayan"] <- "Uruguay"
cases$claimants_nat[cases$claimants_nat == "Private"] <- NA
cases$claimants_nat[cases$claimants_nat == "Swiss"] <- "Switzerland"
cases$claimants_nat[cases$claimants_nat == "Argentine"] <- "Argentina"
cases$claimants_nat[cases$claimants_nat == "Gambian"] <- "Gambia"
cases$claimants_nat[cases$claimants_nat == "ICRS"] <- NA
cases$claimants_nat[cases$claimants_nat == "PHC"] <- NA
cases$claimants_nat[cases$claimants_nat == "Wynne"] <- NA
cases$claimants_nat[cases$claimants_nat == "Services"] <- NA
cases$claimants_nat[cases$claimants_nat == "formerly Capote Farms"] <- NA
cases$claimants_nat[cases$claimants_nat == " Inc."] <- NA
cases$claimants_nat[cases$claimants_nat == "EMELEC"] <- NA
cases$claimants_nat[cases$claimants_nat == "Junior"] <- NA
cases$claimants_nat[cases$claimants_nat == "s"] <- NA
cases$claimants_nat[cases$claimants_nat == "Deutschland"] <- "Germany"
cases$claimants_nat[cases$claimants_nat == "formerly Enron Corporation"] <- NA
cases$claimants_nat[cases$claimants_nat == "Tanzanian"] <- "Tanzania"
cases$claimants_nat[cases$claimants_nat == "Middle East"] <- NA
cases$claimants_nat[cases$claimants_nat == "El Furrial"] <- "Venezuela"
# deleting NAs (can's be merged later) and duplicates
cases <- cases %>% filter(!is.na(claimants_nat)) %>% distinct()

# create "respondent is state owned company" dummy
cases$resp_state_comp <- 0 
cases$resp_state_comp[cases$Respondent.s. == "Boru Hatlari ile Petrol Tasima Anonim Sirketi"] <- 1
cases$resp_state_comp[cases$Respondent.s. == "Perupetro S.A."] <- 1
cases$resp_state_comp[cases$Respondent.s. == "Tanzania Electric Supply Company Limited"] <- 1
cases$resp_state_comp[cases$Respondent.s. == "Bangladesh Petroleum Exploration and Production Company Limited (\"Bapex\") and Bangladesh Oil Gas and Mineral Corporation (\"Petrobangla\")"] <- 1
cases$resp_state_comp[cases$Respondent.s. == "Bangladesh Petroleum Exploration & Production Company Limited (\"Bapex\") and Bangladesh Oil Gas and Mineral Corporation"] <- 1
cases$resp_state_comp[cases$Respondent.s. == "Empresa Estatal Petróleos del Ecuador (Petroecuador)"] <- 1

# correcting quirks in the respondents nationalities & code state comps as their hosts
cases$respondents_nat <- cases$Respondent.s.
cases$respondents_nat[cases$Respondent.s. == "Boru Hatlari ile Petrol Tasima Anonim Sirketi"] <- "Turkey"
cases$respondents_nat[cases$Respondent.s. == "Caravelí Cotaruse Transmisora de Energía S.A.C."] <- NA # private company
cases$respondents_nat[cases$Respondent.s. == "Perupetro S.A."] <- "Peru"
cases$respondents_nat[cases$Respondent.s. == "CMS Energy Corporation and others"] <- NA # private company
cases$respondents_nat[cases$Respondent.s. == "Tanzania Electric Supply Company Limited"] <- "Tanzania"
cases$respondents_nat[cases$Respondent.s. == "Tanzania Electric Supply Company Limited"] <- "Tanzania"
cases$respondents_nat[cases$Respondent.s. == "Bangladesh Petroleum Exploration and Production Company Limited (\"Bapex\") and Bangladesh Oil Gas and Mineral Corporation (\"Petrobangla\")"] <- "Bangladesh"
cases$respondents_nat[cases$Respondent.s. == "Bangladesh Petroleum Exploration & Production Company Limited (\"Bapex\") and Bangladesh Oil Gas and Mineral Corporation"] <- "Bangladesh"
cases$respondents_nat[cases$Respondent.s. == "Republic of Ecuador and Empresa Estatal Petróleos del Ecuador (Petroecuador)"] <- "Ecuador"
cases$respondents_nat[cases$Respondent.s. == "Republic of Ecuador and Consejo Nacional de Electricidad"] <- "Ecuador"
cases$respondents_nat[cases$Respondent.s. == "Empresa Estatal Petróleos del Ecuador (Petroecuador)"] <- "Ecuador"
cases$respondents_nat[cases$Respondent.s. == "Democratic Republic of the Congo and Générale des Carrières et des Mines"] <- "Congo, Democratic Republic"
cases$respondents_nat[cases$Respondent.s. == "Independent Power Tanzania Limited"] <- NA # private company
cases$respondents_nat[cases$Respondent.s. == "Bangladesh and Bangladesh Oil, Gas and Mineral Corporation"] <- "Bangladesh"
cases$respondents_nat[cases$Respondent.s. == "Arab Republic of Egypt and General Authority for Investment and Free Zones"] <- "Egypt"
cases$respondents_nat[cases$Respondent.s. == "Société Serete S.A."] <- NA # private company
cases$respondents_nat[cases$Respondent.s. == "PT Kaltim Prima Coal and others"] <- NA # private company
cases$respondents_nat[cases$Respondent.s. == "United Republic of Cameroon and Société Camerounaise des Engrais"] <- "Cameroon"

# deleting NAs (can's be merged later) and duplicates
cases <- cases %>% filter(!is.na(respondents_nat)) %>% distinct()

## Set up WB codes for respondents and claimants
# load a dataset with references to the WB codes
country.codes <- read.csv("country codes/country codes.csv", sep=";", stringsAsFactors=FALSE)
# code respondents as their WB code and save them as host
# code claimants as their WB codes and save them as source
cases <- cases %>% 
      mutate(host = country.codes$WBcode[match(respondents_nat, country.codes$ICSIDname)],
             source = country.codes$WBcode[match(claimants_nat, country.codes$ICSID2name)])
# also check the alternative ICSID country names and add them
cases$host <- replace(cases$host, 
                      is.na(cases$host), 
                      country.codes$WBcode[match(
                            cases$respondents_nat[is.na(cases$host)], country.codes$ICSIDalt)]
)
cases$host <- replace(cases$host, 
                      is.na(cases$host), 
                      country.codes$WBcode[match(
                            cases$respondents_nat[is.na(cases$host)], country.codes$country)]
)
cases$source <- replace(cases$source, 
                        is.na(cases$source), 
                        country.codes$WBcode[match(
                              cases$claimants_nat[is.na(cases$source)], country.codes$country)]
)
# remove cases with missings on either host or source variable
cases <- cases %>% filter(!is.na(host) & !is.na(source) & host != source) %>% 
      distinct()
# save data
write.csv(cases, "data/cases.csv", append = FALSE)

## Export XLSX file
file_name <- paste0("data/ICSID_cases_reference_", Sys.Date(), ".xlsx")
write.xlsx(cases, file_name, sheetName = "ICSID", 
           col.names = TRUE, row.names = FALSE, append=FALSE, showNA = FALSE)

# To continue run formatting_claims.R
source("formatting_claims.R")